#!/bin/bash
setxkbmap -layout gb -option caps:escape -option altwin:swap_lalt_lwin
xset -b
xrandr --output DP-3 --auto --left-of eDP-1 --rotate normal ; xrandr --output DP-1 --auto --rotate left --left-of DP-3

#xrandr --output DVI-I-3-2 --auto --left-of eDP-1 --rotate normal ; xrandr --output DVI-I-2-1 --auto --rotate normal --left-of DVI-I-3-2

